/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'id' : bigint,
  'service' : ServiceType,
  'status' : InquiryStatus,
  'name' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface InquiryInput {
  'service' : ServiceType,
  'name' : string,
  'phone' : string,
}
export type InquiryStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type ServiceType = { 'voterIdUpdate' : null } |
  { 'panCardNew' : null } |
  { 'aadharCardDownload' : null } |
  { 'voterIdNew' : null } |
  { 'aadharCardUpdate' : null } |
  { 'panCardUpdate' : null } |
  { 'identityCardUpdate' : null } |
  { 'rationCardUpdate' : null } |
  { 'bankAccountOpening' : null } |
  { 'identityCardApplication' : null } |
  { 'aadharCardNew' : null } |
  { 'pmgScheme' : null } |
  { 'rationCardNew' : null } |
  { 'otherGovernmentSchemes' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteInquiry' : ActorMethod<[bigint], undefined>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInquiriesByStatus' : ActorMethod<[InquiryStatus], Array<Inquiry>>,
  'getInquiryById' : ActorMethod<[bigint], Inquiry>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitInquiry' : ActorMethod<[InquiryInput], bigint>,
  'updateInquiryStatus' : ActorMethod<[bigint, InquiryStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];