/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'voterIdUpdate' : IDL.Null,
  'panCardNew' : IDL.Null,
  'aadharCardDownload' : IDL.Null,
  'voterIdNew' : IDL.Null,
  'aadharCardUpdate' : IDL.Null,
  'panCardUpdate' : IDL.Null,
  'identityCardUpdate' : IDL.Null,
  'rationCardUpdate' : IDL.Null,
  'bankAccountOpening' : IDL.Null,
  'identityCardApplication' : IDL.Null,
  'aadharCardNew' : IDL.Null,
  'pmgScheme' : IDL.Null,
  'rationCardNew' : IDL.Null,
  'otherGovernmentSchemes' : IDL.Null,
});
export const InquiryStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'service' : ServiceType,
  'status' : InquiryStatus,
  'name' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const InquiryInput = IDL.Record({
  'service' : ServiceType,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInquiriesByStatus' : IDL.Func(
      [InquiryStatus],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'getInquiryById' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitInquiry' : IDL.Func([InquiryInput], [IDL.Nat], []),
  'updateInquiryStatus' : IDL.Func([IDL.Nat, InquiryStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'voterIdUpdate' : IDL.Null,
    'panCardNew' : IDL.Null,
    'aadharCardDownload' : IDL.Null,
    'voterIdNew' : IDL.Null,
    'aadharCardUpdate' : IDL.Null,
    'panCardUpdate' : IDL.Null,
    'identityCardUpdate' : IDL.Null,
    'rationCardUpdate' : IDL.Null,
    'bankAccountOpening' : IDL.Null,
    'identityCardApplication' : IDL.Null,
    'aadharCardNew' : IDL.Null,
    'pmgScheme' : IDL.Null,
    'rationCardNew' : IDL.Null,
    'otherGovernmentSchemes' : IDL.Null,
  });
  const InquiryStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'service' : ServiceType,
    'status' : InquiryStatus,
    'name' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const InquiryInput = IDL.Record({
    'service' : ServiceType,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInquiriesByStatus' : IDL.Func(
        [InquiryStatus],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getInquiryById' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitInquiry' : IDL.Func([InquiryInput], [IDL.Nat], []),
    'updateInquiryStatus' : IDL.Func([IDL.Nat, InquiryStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };