/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface InquiryInput {
    service: ServiceType;
    name: string;
    phone: string;
}
export interface Inquiry {
    id: bigint;
    service: ServiceType;
    status: InquiryStatus;
    name: string;
    timestamp: Time;
    phone: string;
}
export enum InquiryStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum ServiceType {
    voterIdUpdate = "voterIdUpdate",
    panCardNew = "panCardNew",
    aadharCardDownload = "aadharCardDownload",
    voterIdNew = "voterIdNew",
    aadharCardUpdate = "aadharCardUpdate",
    panCardUpdate = "panCardUpdate",
    identityCardUpdate = "identityCardUpdate",
    rationCardUpdate = "rationCardUpdate",
    bankAccountOpening = "bankAccountOpening",
    identityCardApplication = "identityCardApplication",
    aadharCardNew = "aadharCardNew",
    pmgScheme = "pmgScheme",
    rationCardNew = "rationCardNew",
    otherGovernmentSchemes = "otherGovernmentSchemes"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteInquiry(id: bigint): Promise<void>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    getCallerUserRole(): Promise<UserRole>;
    getInquiriesByStatus(status: InquiryStatus): Promise<Array<Inquiry>>;
    getInquiryById(id: bigint): Promise<Inquiry>;
    isCallerAdmin(): Promise<boolean>;
    submitInquiry(input: InquiryInput): Promise<bigint>;
    updateInquiryStatus(id: bigint, status: InquiryStatus): Promise<void>;
}
import type { Inquiry as _Inquiry, InquiryInput as _InquiryInput, InquiryStatus as _InquiryStatus, ServiceType as _ServiceType, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteInquiry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInquiry(arg0);
            return result;
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInquiriesByStatus(arg0: InquiryStatus): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiriesByStatus(to_candid_InquiryStatus_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiriesByStatus(to_candid_InquiryStatus_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInquiryById(arg0: bigint): Promise<Inquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiryById(arg0);
                return from_candid_Inquiry_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiryById(arg0);
            return from_candid_Inquiry_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async submitInquiry(arg0: InquiryInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(to_candid_InquiryInput_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(to_candid_InquiryInput_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateInquiryStatus(arg0: bigint, arg1: InquiryStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInquiryStatus(arg0, to_candid_InquiryStatus_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInquiryStatus(arg0, to_candid_InquiryStatus_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_InquiryStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryStatus): InquiryStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Inquiry_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    service: _ServiceType;
    status: _InquiryStatus;
    name: string;
    timestamp: _Time;
    phone: string;
}): {
    id: bigint;
    service: ServiceType;
    status: InquiryStatus;
    name: string;
    timestamp: Time;
    phone: string;
} {
    return {
        id: value.id,
        service: from_candid_ServiceType_n6(_uploadFile, _downloadFile, value.service),
        status: from_candid_InquiryStatus_n8(_uploadFile, _downloadFile, value.status),
        name: value.name,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    voterIdUpdate: null;
} | {
    panCardNew: null;
} | {
    aadharCardDownload: null;
} | {
    voterIdNew: null;
} | {
    aadharCardUpdate: null;
} | {
    panCardUpdate: null;
} | {
    identityCardUpdate: null;
} | {
    rationCardUpdate: null;
} | {
    bankAccountOpening: null;
} | {
    identityCardApplication: null;
} | {
    aadharCardNew: null;
} | {
    pmgScheme: null;
} | {
    rationCardNew: null;
} | {
    otherGovernmentSchemes: null;
}): ServiceType {
    return "voterIdUpdate" in value ? ServiceType.voterIdUpdate : "panCardNew" in value ? ServiceType.panCardNew : "aadharCardDownload" in value ? ServiceType.aadharCardDownload : "voterIdNew" in value ? ServiceType.voterIdNew : "aadharCardUpdate" in value ? ServiceType.aadharCardUpdate : "panCardUpdate" in value ? ServiceType.panCardUpdate : "identityCardUpdate" in value ? ServiceType.identityCardUpdate : "rationCardUpdate" in value ? ServiceType.rationCardUpdate : "bankAccountOpening" in value ? ServiceType.bankAccountOpening : "identityCardApplication" in value ? ServiceType.identityCardApplication : "aadharCardNew" in value ? ServiceType.aadharCardNew : "pmgScheme" in value ? ServiceType.pmgScheme : "rationCardNew" in value ? ServiceType.rationCardNew : "otherGovernmentSchemes" in value ? ServiceType.otherGovernmentSchemes : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): InquiryStatus {
    return "cancelled" in value ? InquiryStatus.cancelled : "pending" in value ? InquiryStatus.pending : "completed" in value ? InquiryStatus.completed : "inProgress" in value ? InquiryStatus.inProgress : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n4(_uploadFile, _downloadFile, x));
}
function to_candid_InquiryInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryInput): _InquiryInput {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_InquiryStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): _InquiryStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    service: ServiceType;
    name: string;
    phone: string;
}): {
    service: _ServiceType;
    name: string;
    phone: string;
} {
    return {
        service: to_candid_ServiceType_n16(_uploadFile, _downloadFile, value.service),
        name: value.name,
        phone: value.phone
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == InquiryStatus.cancelled ? {
        cancelled: null
    } : value == InquiryStatus.pending ? {
        pending: null
    } : value == InquiryStatus.completed ? {
        completed: null
    } : value == InquiryStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    voterIdUpdate: null;
} | {
    panCardNew: null;
} | {
    aadharCardDownload: null;
} | {
    voterIdNew: null;
} | {
    aadharCardUpdate: null;
} | {
    panCardUpdate: null;
} | {
    identityCardUpdate: null;
} | {
    rationCardUpdate: null;
} | {
    bankAccountOpening: null;
} | {
    identityCardApplication: null;
} | {
    aadharCardNew: null;
} | {
    pmgScheme: null;
} | {
    rationCardNew: null;
} | {
    otherGovernmentSchemes: null;
} {
    return value == ServiceType.voterIdUpdate ? {
        voterIdUpdate: null
    } : value == ServiceType.panCardNew ? {
        panCardNew: null
    } : value == ServiceType.aadharCardDownload ? {
        aadharCardDownload: null
    } : value == ServiceType.voterIdNew ? {
        voterIdNew: null
    } : value == ServiceType.aadharCardUpdate ? {
        aadharCardUpdate: null
    } : value == ServiceType.panCardUpdate ? {
        panCardUpdate: null
    } : value == ServiceType.identityCardUpdate ? {
        identityCardUpdate: null
    } : value == ServiceType.rationCardUpdate ? {
        rationCardUpdate: null
    } : value == ServiceType.bankAccountOpening ? {
        bankAccountOpening: null
    } : value == ServiceType.identityCardApplication ? {
        identityCardApplication: null
    } : value == ServiceType.aadharCardNew ? {
        aadharCardNew: null
    } : value == ServiceType.pmgScheme ? {
        pmgScheme: null
    } : value == ServiceType.rationCardNew ? {
        rationCardNew: null
    } : value == ServiceType.otherGovernmentSchemes ? {
        otherGovernmentSchemes: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
